### ISSUE TITLE
Supporting windows for running test from GUI

### ISSUE THREAD

**Issue by mrz-gh** [yuravg/uvm_tb_cross_bar#1]
By replacing the following code in `sim/Makefile , the tests can be run in Windows.

    ifeq ($(OS),Windows_NT)
    # Windows-specific
    wlib:
        @if not exist work ( \
            vlib work \
        )
        vmap work work
    else
    # Linux-specific
    wlib:
        @-if [ ! -d work ] ; then \
        vlib work;              \
        fi
        vmap work work
    endif

**Comment by yuravg** [comment]
Thanks for the suggestion.
You can't run GUI modeling without changing the make-file?

In Windows OS, MSYS2 I have no problem with this make-file. 
Moreover, the 'wlib' target in this make-file (with commands: vlib work; vmap work work) 
is not needed and I will remove it as soon as I change this project.

**Comment by mrz-gh** [comment]
> Thanks for the suggestion.
> You can't run GUI modeling without changing the make-file?
> 
> In Windows OS, MSYS2 I have no problem with this make-file. 
> Moreover, the 'wlib' target in this make-file (with commands: vlib work; vmap work work) 
> is not needed and I will remove it as soon as I change this project.

No, I couldn't run tests in the transcript CLI of the QuestSim because the '!' was reported as an error and wasn't supported or recognized by the shell of transcript version. Although, I use MinGW instead of MSYS2. So, it might be the problem.

Thanks

**Comment by yuravg** [comment]
> because the '!' was reported as an error and wasn't supported or recognized by the shell of transcript version

I agree.
 I checked in the minimal (available to me) version of questasim64_10.7c and GNU bash, version 5.1.16(1)-release (x86_64-pc-msys) and did not see the problem. Also works if I delete the target 'wlib' and its calls (as I wrote earlier)

**Comment by mrz-gh** [comment]
> > because the '!' was reported as an error and wasn't supported or recognized by the shell of transcript version
> 
> I agree.
>  I checked in the minimal (available to me) version of questasim64_10.7c and GNU bash, version 5.1.16(1)-release (x86_64-pc-msys) and did not see the problem. Also works if I delete the target 'wlib' and its calls (as I wrote earlier)
> 
> 

Thank you. It would be great if you do that as soon as you can.
Also, it would be great if you could draw the diagram of the UVM components and how they are connected to each other. Actually, It took me 2 days  to grasp your code. There is little comment and no documents. It is a pity that such a great UVM example is hard to figure out.

Best,

**Comment by yuravg** [comment]
I hope this [7e3de41](https://github.com/yuravg/uvm_tb_cross_bar/commit/7e3de41df1e18449f36249badb8209df4e40b44d) will fix this problem for you.

> Also, it would be great if you could draw the diagram .....

I agree, 
I'll try to add a diagram and description, but not anytime soon.

**Comment by mrz-gh** [comment]
It is ok by me. Thanks.
